name = "Minecraft Pack"
author = "arno"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "daa2e4205556c25f703e442c9c3c7b82a3cd50c9f5886d585e7b76a1cb314e2b"

[versions]
forge = "47.4.21"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
