name = "Minecraft Pack"
author = "arno"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f6ae3f3e5b8fb9603b6c6d7a5fa6065e9fcd4a7e6a5e6dae3a80483905830388"

[versions]
forge = "47.4.21"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
