name = "Minecraft Pack"
author = "arno"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "508003d7819933d8d331a66bd5cdca8f08fe0b1eb8c71312fc64e0320eefb8ee"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.244"
